compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmPublishAccess: public
npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - workspaces/local/bundles/@yarnpkg/plugin-local-development.js
  - path: ./workspaces/plugins/gitversion/bundle/gitversion.js
  - path: ./workspaces/plugins/gitversion-ms-teams/bundle/gitversion-ms-teams.js
  - path: ./workspaces/plugins/gitversion-azure-devops/bundle/gitversion-azure-devops.js

yarnPath: .yarn/releases/yarn-4.0.2.cjs
