nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: "./workspaces/plugins/gitversion/bundles/@yarnpkg/plugin-gitversion.js"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

npmPublishAccess: public