nodeLinker: pnp

npmPublishAccess: public

plugins:
  - workspaces/local/bundles/@yarnpkg/plugin-local-development.js
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: ./workspaces/plugins/gitversion/bundle/gitversion.js
  - path: ./workspaces/plugins/gitversion-ms-teams/bundle/gitversion-ms-teams.js
  - path: ./workspaces/plugins/gitversion-azure-devops/bundle/gitversion-azure-devops.js
  
yarnPath: .yarn/releases/yarn-3.5.0.cjs